### ISSUE TITLE
No release under Releases and solution does not compile.

### ISSUE THREAD

**Issue by guppysb** [TheManta/Faith#1]
Hi,

There doesn't seem to be any release under Releases and the solution does not compile due to missing ff14bot references. Where can I find the library for the ff14 bot?

Thank you taking the time to read this.

**Comment by TheManta** [comment]
Hello,

Faith isn't ready to be used yet, but auto-builds are already configured to upload to Releases when it's time.  Auto-updating on bot launch is also planned.  Please bear with me and maybe join the [Discord](https://discord.gg/4Y5HSjP) for progress commentary.  The short version is enough prototype exists to queue and complete the first boss, but a lot of rough edges need to be sanded off and I'm targeting late November to early December for a functional release.

For now, consider using [RB.Trust](https://github.com/TheManta/RBtrust) with [Magitek](https://discord.gg/rDsFbKr) and [Cyril](https://github.com/sodimm/RebornBuddy).  The linked fork fixes retainer window spam when queuing for Trusts.  Disable repairs in RB.Trust and let Cyril handle that to prevent hard crashes.

If you still want to build Faith yourself, the missing assemblies can be resolved by adding the custom NuGet feed for [RB.Assemblies](https://github.com/TheManta/RB.Assemblies#usage).  Instructions in the link.

Thanks for the interest!  Hope to have it working soon.

**Comment by guppysb** [comment]
Awesome, really excited to try it out. Thanks for all the work.
